// ─────────────────────────────────────────────────────────────
//  MTGRP — Project Registry
//
//  FILE IDs are chronological: p01 = oldest, p12 = newest.
//  Add new projects at the TOP of this array with the next
//  number (p13, p14...). The site always shows newest first.
//
//  Fields:
//    id            — filename without .html  (e.g. "p13")
//    title         — full project title
//    subtitle      — typology / competition result / etc.
//    desc          — paragraph shown in sidebar of project page
//    location      — city / country
//    type          — programme type
//    size          — floor area or scale
//    budget        — if disclosed, otherwise "—"
//    status        — Built / Competition / In progress / etc.
//    photos        — number of photo slots to generate
//    team          — array of strings, project team members
//    collaborators — array of strings, external firms / people
// ─────────────────────────────────────────────────────────────

const PROJECTS = [

  // ── NEWEST FIRST — add new projects at the top with next id ──

  {
    id: "p13",
    title: "A Home in the Sun",
    subtitle: "Home for Seniors",
    desc: "An elderly care facility organized around the natural circadian rhythm to mitigate the disorientation associated with dementia. The architecture establishes a clear structural dichotomy: a dense, in-situ concrete communal core consolidates daytime collective programs, while prefabricated timber wings hold the private, quiet residential households. Designed as a replicable prototype, the modular kit of parts adapts to two distinct topographies. In Lysá nad Labem, the households are compacted into a three-storey pinwheel forming an urban edge, whereas in Milovice, the same units unfold into a two-storey horizontal arrangement following the gentle slope of the land. The project relies on passive climate strategies, utilizing high thermal mass and cross-ventilation, while the landscape functions as an active therapeutic instrument calibrated to provide temporal and olfactory orientation.",
    location: "Lysá nad Labem. CZ",
    type: "Housing",
    size: "—",
    budget: "212,227,500 Kč",
    status: "Competition",
    photos: 10,
    team: ["Andrew Georges", "Charbel Abou Chacra", "Nahi El Khoury", "Jorge Sanchez Bajo"],
    collaborators: ["tebt+"],
  },
  {
    id: "p11",
    title: "Die Den Gletscher Bewohnen",
    subtitle: "Europan — Winner",
    desc: "Winning entry for the Europan competition. The project addresses the geological threshold between molasse and moraine, proposing a model of dwelling that is responsive to the terrain, water, and social change. The glacier is not backdrop but partner — a slow, material presence that shapes the logic of the building.",
    location: "St. Galen, CH",
    type: "Competition",
    size: "12.4 ha",
    budget: "—",
    status: "Winner",
    photos: 5,
    team: ["Andrew Georges, Jorge Sanchez Bajo, Bettina Kagelmacher, Roman Schober"],
    collaborators: ["tebt+","Bettina Kagelmacher", "Roman Schober"],
  },
  {
    id: "p10",
    title: "Holcim Visitor Center",
    subtitle: "Competition Entry",
    desc: "Competition entry for the Holcim Visitor Center. Positioned as a precise interface between industrial production and the public, the proposal engages with the material logic of cement. The building acts as a transparent, functional framework rather than a conventional shell, performing its own material origin while physically manifesting the circular economy and flexible, future-proof architectural design.",
    location: "Siggenthal, CH",
    type: "Cultural",
    size: "—",
    budget: "—",
    status: "Competition entry",
    photos: 5,
    team: ["Andrew Georges, Jorge Sanchez Bajo, Bettina Kagelmacher, Roman Schober"],
    collaborators: ["tebt+","Bettina Kagelmacher", "Roman Schober"],
  },
  {
    id: "p09",
    title: "Santa María de Valdeiglesias",
    subtitle: "Adaptive Reuse — 2nd Prize",
    desc: "Second prize in the competition for the adaptive reuse of the monastery of Santa María de Valdeiglesias. The project negotiates between the preserved fabric of a historic religious complex and a contemporary programme for collective inhabitation — working with rather than against the existing spatial hierarchies of monastic life.",
    location: "Pelayos de la Presa, ES",
    type: "Heritage / Adaptive Reuse",
    size: "—",
    budget: "—",
    status: "2nd Prize",
    photos: 6,
    team: ["Andrew Georges", "Nahi El Khoury", "Joe Chamata"],
    collaborators: [],
  },
  {
    id: "p08",
    title: "Papushevo Park",
    subtitle: "Urban Development",
    desc: "An urban development combining a public park, kindergarten, and office buildings. The park is the structuring element of the ensemble, a ground that organises collective life rather than filling residual space between built volumes.",
    location: "Papushevo, RU",
    type: "Urban / Mixed Use",
    size: "—",
    budget: "—",
    status: "—",
    photos: 7,
    team: ["Andrew Georges", "Charbel Abou Chacra", "Nahi El Khoury", "Joe Chamata","Mike Chaiban"],
    collaborators: [],
  },
  {
    id: "p07",
    title: "Casa de Aperos",
    subtitle: "Collective Housing",
    desc: "A proposal for a self-sufficient commune in Eivissa grounded in principles of degrowth and scarcity. Conceived as an adaptable infrastructure stripped to its basic conditions, the project utilizes a proximity modular system constructed from salvaged local demolition materials. Learning from the vernacular Casa Payesa, it adapts traditional mass and passive climate strategies for collective living. The architecture actively engages the user in sustainable practices, functioning alongside an operational manual to reduce traditional energy consumption.",
    location: "Eivissa, ES",
    type: "Housing",
    size: "—",
    budget: "—",
    status: "—",
    photos: 10,
    team: ["Andrew Georges", "Jorge Sanchez Bajo", "Andres Solano"],
    collaborators: ["tebt+","esteoeste estudio"],
  },
  {
    id: "p06c",
    title: "Salt Nest",
    subtitle: "Adaptive Reuse",
    desc: "Perched on a rugged Sicilian cliff, the Salt Nest breathes new life into an abandoned stone Customs House, transforming a historic relic into an immersive visitor retreat. Embracing principles of material circularity and structural minimalism, the design introduces translucent, geometric roof volumes clad in crystallized salt panels grown sustainably from the surrounding Mediterranean Sea. Inside, the reimagined interior unfolds vertically, hosting a coffee shop, reading nooks, and a layered museum sequence that culminates in a delicate rooftop observation deck suspended between the earth and the sky. Ultimately, the intervention engages in a quiet dialogue with the raw coastal landscape and the ghosts of its past, offering visitors a poetic connection to light, terrain, and the natural elements.",
    location: "Punta Bianca, IT",
    type: "Visitor Center / Pavilion",
    size: "—",
    budget: "—",
    status: "—",
    photos: 7,
    team: ["Joe Chamata","Christina Karam","Andrey Bader"],
    collaborators: [],
  },
  {
    id: "p06b",
    title: "Three Brothers",
    subtitle: "Three Pavilions",
    desc: "Three pavilions for three brothers on the coast of Amchit, Lebanon. Each pavilion is distinct — a singular response to a shared site — while the three together constitute a small domestic landscape on the water's edge.",
    location: "Amchit, Lebanon",
    type: "Residential / Pavilion",
    size: "—",
    budget: "—",
    status: "—",
    photos: 7,
    team: ["Andrew Georges"],
    collaborators: [],
  },
  {
    id: "p06",
    title: "Cárcel Abierta",
    subtitle: "Adaptive Reuse",
    desc: "Adaptive reuse of a prison in Chile. The project addresses the conversion of a site of confinement into a structure for collective life — working through the existing spatial order of the penitentiary as an architectural argument about openness and enclosure.",
    location: "Talca, CL",
    type: "Heritage / Adaptive Reuse",
    size: "—",
    budget: "—",
    status: "—",
    photos: 5,
    team: ["Andrew Georges", "Nahi El Khoury", "MZ", "BSJ"],
    collaborators: ["CL","NNDO"],
  },
  {
    id: "p05b",
    title: "Above All, a Shared Resource",
    subtitle: "Ephemeral Installation",
    desc: "Pliée: A blank piece of paper offers infinite experimentation and as structuralists we began with a fold. Pliée is a wooden structure inspired by the mechanism of simple origami. The folded structure is meant to define its own parameters and create functional spaces on the roof through shading mechanisms while the roof’s connection to the sky is defined, intentional, and purposeful while remaining flexible and mobile.",
    location: "Beirut, LB",
    type: "Public / Ephemeral",
    size: "—",
    budget: "600$",
    status: "—",
    photos: 5,
    team: ["Joe Chamata", "Mike Chaiban", "Christina Karam"],
    collaborators: ["Bits to Atoms"],
  },
  {
    id: "p05",
    title: "Amchit Fire Proving Grounds",
    subtitle: "Ephemeral Station",
    desc: "A temporary firefighter training station in Amchit, Lebanon — designed to transform into a public park for children once its operational phase is complete. A single structure serving two sequential programmes, using material and landscape logic to negotiate the transition between them.",
    location: "Amchit, LB",
    type: "Public / Ephemeral",
    size: "—",
    budget: "—",
    status: "—",
    photos: 5,
    team: ["Andrew Georges", "Charbel Abou Chacra", "Nahi El Khoury", "Joe Chamata"],
    collaborators: [],
  },
  {
    id: "p04",
    title: "Dancing House",
    subtitle: "Adaptive Reuse & Coliving",
    desc: "A collaborative adaptive project for a traditional house in Beit Mery. The existing structure is adapted for a coliving situation with communal activities, and the garden is populated with a series of follies that extend the collective life of the house into the landscape.",
    location: "Beit Mery, LB",
    type: "Residential / Coliving",
    size: "—",
    budget: "—",
    status: "—",
    photos: 6,
    team: ["Andrew Georges", "Charbel Abou Chacra", "Nahi El Khoury", "Joe Chamata","Mike Chaiban"],
    collaborators: [],
  },
  {
    id: "p03",
    title: "RAZ House",
    subtitle: "Interior Design",
    desc: "Interior design for a duplex apartment. A wooden box organized life accross two floors.",
    location: "Aley, LB",
    type: "Interior Design",
    size: "Duplex — 2 floors",
    budget: "—",
    status: "—",
    photos: 2,
    team: ["Andrew Georges", "Charbel Abou Chacra", "Nahi El Khoury", "Joe Chamata","Mike Chaiban"],
    collaborators: [],
  },
  {
    id: "p03b",
    title: "AM House",
    subtitle: "Interior Design",
    desc: "Interior design for a penthouse. A steel platform forms a mezanine organizing life underneath it.",
    location: "Nahr Ibrahim, LB",
    type: "Interior Design",
    size: "Penthouse",
    budget: "—",
    status: "—",
    photos: 2,
    team: ["Andrew Georges", "Charbel Abou Chacra", "Nahi El Khoury", "Joe Chamata","Jaques Zekian"],
    collaborators: [],
  },
  {
    id: "p03c",
    title: "GOE Office Extension",
    subtitle: "Interior Design",
    desc: "xxxxxxxxxxx",
    location: "xxxxxxx, LB",
    type: "Interior Design",
    size: "Penthouse",
    budget: "—",
    status: "—",
    photos: 2,
    team: ["Andrew Georges", "Charbel Abou Chacra"],
    collaborators: [],
  },
  {
    id: "p02",
    title: "Baglietto Pavilion",
    subtitle: "Competition — Honourable Mention",
    desc: "Competition entry for the Baglietto Pavilion, receiving an honourable mention. A proposal exploring temporary structure, public presence, and the architecture of gathering — a single gesture that is simultaneously enclosure and threshold.",
    location: "—",
    type: "Pavilion / Competition",
    size: "—",
    budget: "—",
    status: "Honourable Mention",
    photos: 4,
    team: [ "Nahi El Khoury", "Valerie Saab"],
    collaborators: [],
  },
  {
    id: "p01",
    title: "KWL — Beirut River",
    subtitle: "Competition — 1st Prize",
    desc: "First prize in the KWL competition. The project reframes the infrastructure of the Beirut River as a site of meeting — proposing that the engineered channel, rather than dividing, can become the basis for a new form of urban public space. Infrastructure as meeting place.",
    location: "Beirut, LB",
    type: "Infrastructure / Public Space",
    size: "—",
    budget: "—",
    status: "1st Prize",
    photos: 6,
    team: ["Charbel Abou Chacra", "Nahi El Khoury", "Kay Bardawil", "Charbel Corbani", "????"],
    collaborators: [],
  },

];
